name: lxd
version: 0.15-0
vendor: "Stéphane Graber <stgraber@ubuntu.com>"
icon: meta/lxd.png
type: framework
architecture: [amd64, armhf]
source: https://github.com/lxc
ports:
  external:
    lxd:
      port: 8443/tcp
      negotiable: no
services:
 - name: lxd
   description: "The LXD container lightervisor"
   start: wrappers/lxd.start
   stop: wrappers/lxd.stop
   security-policy:
    apparmor: meta/lxd.apparmor
    seccomp: meta/lxd.seccomp
binaries:
 - name: wrappers/lxc
   description: "LXD command line client"
   caps:
    - networking
 - name: wrappers/lxd-images
   description: "LXD image importer"
   security-policy:
    apparmor: meta/lxd.apparmor
   caps:
    - networking
